version: '3.8'

services:
  mongo:
    image: mongo:7.0
    container_name: mongo_habitaciones
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - habitacion_network

  habitacion_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: habitacion_service
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - MongoDB__ConnectionString=mongodb://mongo:27017
      - MongoDB__Database=habitacionesdb
      - MongoDB__HabitacionesCollection=habitaciones
      - Jwt__Key=EstaEsUnaClaveMuySeguraDeAlMenos32Bytes!
    depends_on:
      - mongo
    networks:
      - habitacion_network

volumes:
  mongo_data:

networks:
  habitacion_network:
    driver: bridge
