services:
  agendas_app:
    build: .
    ports:
      - "4001:4000"
    environment:
      - PORT=4000
      - MONGO_URI=mongodb://db:27017/agenda_f
      - JWT_SECRET=no_es_una_contraseña_pero_suena_segura_y_si_la_ves_no_la_uses_ni_la_copies_porfa_gracias
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  db:
    image: mongo:6.0
    environment:
      MONGO_INITDB_DATABASE: agenda_f
    ports:
      - "27018:27017"
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
