services:
  reservas_app:
    build: .
    ports:
      - "5001:5000"
    environment:
      - DATABASE_URL=postgresql://usuario:contraseña@db:5432/reserva_f
      - JWT_SECRET=no_es_una_contraseña_pero_suena_segura_y_si_la_ves_no_la_uses_ni_la_copies_porfa_gracias
      - FLASK_APP=app.py
      - FLASK_ENV=development
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
    command: sh -c "flask db upgrade && python app.py"

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: reserva_f
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: contraseña
    ports:
      - "5433:5432"
    volumes:
      - flask_postgress_data:/var/lib/postgresql/data

volumes:
  flask_postgress_data:
